services:
  cosmos-db-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmos-db-emulator
    mem_limit: 3g
    cpu_count: 2
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    ports:
      - "8081:8081"      # Portal
      - "10251:10251"    # Service endpoint
      - "10252:10252"    # SDK endpoint
      - "10253:10253"    # HTTPS emulator config endpoint
      - "10254:10254"    # Https gateway endpoint
    volumes:
      - cosmos-data:/data/db
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8081/_explorer/emulator.pem"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - foodpal-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - COSMOS_ENDPOINT=${COSMOS_ENDPOINT:-https://cosmos-db-emulator:8081}
      - COSMOS_KEY=${COSMOS_KEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==}
      - COSMOS_DATABASE=${COSMOS_DATABASE:-foodpal-dev}
      - COSMOS_EMULATOR_ENDPOINT=https://cosmos-db-emulator:8081
      - USE_COSMOS_EMULATOR=${USE_COSMOS_EMULATOR:-true}
      - SECRET_KEY=${SECRET_KEY}
      - AZURE_AD_B2C_TENANT_NAME=${AZURE_AD_B2C_TENANT_NAME}
      - AZURE_AD_B2C_CLIENT_ID=${AZURE_AD_B2C_CLIENT_ID}
      - AZURE_AD_B2C_CLIENT_SECRET=${AZURE_AD_B2C_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    depends_on:
      - cosmos-db-emulator
    networks:
      - foodpal-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    restart: always
    networks:
      - foodpal-network

networks:
  foodpal-network:
    driver: bridge

volumes:
  cosmos-data:
    driver: local
